### ISSUE TITLE
Tracking initial function implementation

### ISSUE THREAD

**Issue by tiehuis** [tiehuis/zig-fmath#2]
Tracking initial implementation passing basic sanity tests. No rounding mode selection or flag set.

 - [x] fma
    - [x] f32
    - [x] f64
 - [x] nan
    - [x] f32
    - [x] f64
 - [x] abs
    - [x] f32
    - [x] f64
 - [x] exp
    - [x] f32
    - [x] f64
 - [x] exp2
    - [x] f32
    - [x] f64
 - [x] expm1
    - [x] f32
    - [x] f64
 - [x] log
    - [x] f32
    - [x] f64
 - [x] log2
    - [x] f32
    - [x] f64
 - [x] log10
    - [x] f32
    - [x] f64
 - [x] log1p
    - [x] f32
    - [x] f64
 - [x] ilogb
    - [x] f32
    - [x] f64
 - [x] sqrt
    - [x] f32
    - [x] f64
 - [x] cbrt
    - [x] f32
    - [x] f64
 - [x] hypot
    - [x] f32
    - [x] f64
 - [x] pow
    - [x] f32
    - [x] f64
 - [x] sin
    - [x] f32
    - [x] f64
 - [x] cos
    - [x] f32
    - [x] f64
 - [x] tan
    - [x] f32
    - [x] f64
 - [x] asin
    - [x] f32
    - [x] f64
 - [x] acos
    - [x] f32
    - [x] f64
 - [x] atan
    - [x] f32
    - [x] f64
 - [x] atan2
    - [x] f32
    - [x] f64
 - [x] sinh
    - [x] f32
    - [x] f64
 - [x] cosh
    - [x] f32
    - [x] f64
 - [x] tanh
    - [x] f32
    - [x] f64
 - [x] asinh
    - [x] f32
    - [x] f64
 - [x] acosh
    - [x] f32
    - [x] f64
 - [x] atanh
    - [x] f32
    - [x] f64
 - [x] ceil
    - [x] f32
    - [x] f64
 - [x] floor
    - [x] f32
    - [x] f64
 - [x] trunc
    - [x] f32
    - [x] f64
 - [x] round
    - [x] f32
    - [x] f64
 - [x] frexp
    - [x] f32
    - [x] f64
 - [x] copysign
    - [x] f32
    - [x] f64
 - [x] scalbn
    - [x] f32
    - [x] f64
 - [x] isfinite
    - [x] f32
    - [x] f64
 - [x] isinf
    - [x] f32
    - [x] f64
 - [x] isnan
    - [x] f32
    - [x] f64
 - [x] isnormal
    - [x] f32
    - [x] f64
 - [x] signbit
    - [x] f32
    - [x] f64

**Comment by andrewrk** [comment]
This is coming along great! This is a huge contribution to the zig project.

**Comment by andrewrk** [comment]
Inspired by this effort I started working on ability to print floating point numbers using the errol3 algorithm: https://github.com/zig-lang/zig/compare/errol

Just wanted to let you know so we don't clobber each other's efforts.
